#!/bin/bash

convert favicon.png -resize 72 platforms/android/res/mipmap-hdpi/icon.png
convert favicon.png -resize 36 platforms/android/res/mipmap-ldpi/icon.png
convert favicon.png -resize 48 platforms/android/res/mipmap-mdpi/icon.png
convert favicon.png -resize 96 platforms/android/res/mipmap-xhdpi/icon.png
convert favicon.png -resize 144 platforms/android/res/mipmap-xxhdpi/icon.png
convert favicon.png -resize 192 platforms/android/res/mipmap-xxxhdpi/icon.png



